-- Module 1

-- Hangar
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (1, 'HNG-IST-01', 12, 'Istanbul Airport (IST)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (2, 'HNG-IST-02', 8, 'Istanbul Airport (IST)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (3, 'HNG-ESB-01', 5, 'Ankara Esenboga (ESB)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (4, 'HNG-ADB-01', 6, 'Izmir Adnan Menderes (ADB)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (5, 'HNG-AYT-01', 10, 'Antalya Airport (AYT)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (6, 'HNG-SAW-01', 15, 'Sabiha Gokcen (SAW)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (7, 'HNG-ADA-01', 4, 'Adana Airport (ADA)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (8, 'HNG-TZX-01', 3, 'Trabzon Airport (TZX)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (9, 'HNG-BJV-01', 4, 'Milas-Bodrum (BJV)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (10, 'HNG-DLM-01', 4, 'Dalaman Airport (DLM)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (11, 'HNG-GZT-01', 3, 'Gaziantep Airport (GZT)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (12, 'HNG-ASR-01', 2, 'Kayseri Erkilet (ASR)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (13, 'HNG-KYA-01', 3, 'Konya Airport (KYA)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (14, 'HNG-MLX-01', 2, 'Malatya Erhac (MLX)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (15, 'HNG-NAV-01', 2, 'Nevsehir Kapadokya (NAV)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (16, 'HNG-DNZ-01', 2, 'Denizli Cardak (DNZ)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (17, 'HNG-DIY-01', 4, 'Diyarbakir Airport (DIY)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (18, 'HNG-ERZ-01', 3, 'Erzurum Airport (ERZ)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (19, 'HNG-AOE-01', 2, 'Eskisehir Hasan Polatkan (AOE)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (20, 'HNG-SZX-01', 3, 'Siirt Airport (SZX)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (21, 'HNG-BZR-01', 2, 'Balikesir Merkez (BZR)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (22, 'HNG-VAN-01', 3, 'Van Ferit Melen (VAN)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (23, 'HNG-GNY-01', 2, 'Sanliurfa GAP (GNY)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (24, 'HNG-SZF-01', 4, 'Samsun Carsamba (SZF)');
INSERT INTO Hangar (Hangar_ID, Hangar_Code, Capacity_Aircraft_Count, Location_Airport) VALUES (25, 'HNG-VAS-01', 2, 'Sivas Nuri Demirag (VAS)');

-- Aircraft 
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (101, 1, 'TC-JGA', 2015, 24500, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (102, 1, 'TC-JGB', 2016, 22100, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (103, 2, 'TC-JGC', 2012, 35000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (104, 3, 'TC-JGD', 2018, 18000, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (105, 4, 'TC-JGE', 2020, 10500, 'Standby');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (106, 5, 'TC-LAA', 2019, 15200, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (107, 6, 'TC-LAB', 2014, 29000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (108, 1, 'TC-LAC', 2022, 5400, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (109, 2, 'TC-LAD', 2011, 41000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (110, 3, 'TC-LAE', 2021, 8900, 'Standby');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (111, 7, 'TC-SNA', 2017, 21000, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (112, 5, 'TC-SNB', 2013, 33500, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (113, 6, 'TC-SNC', 2019, 16000, 'Standby');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (114, 4, 'TC-SND', 2015, 26000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (115, 1, 'TC-SNE', 2023, 1200, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (116, 8, 'TC-YAA', 2016, 23000, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (117, 9, 'TC-YAB', 2015, 24100, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (118, 10, 'TC-YAC', 2018, 14000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (119, 11, 'TC-YAD', 2017, 19500, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (120, 12, 'TC-YAE', 2020, 9200, 'Standby');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (121, 13, 'TC-ZAA', 2014, 28500, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (122, 17, 'TC-ZAB', 2013, 31000, 'Maintenance');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (123, 20, 'TC-ZAC', 2021, 6200, 'Active');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (124, 22, 'TC-ZAD', 2019, 13400, 'Standby');
INSERT INTO Aircraft (Aircraft_ID, Hangar_ID, Tail_Reg_No, Production_Year, Current_Flight_Hour, Flight_Status) VALUES (125, 24, 'TC-ZAE', 2022, 4800, 'Active');

-- Aircraft_Component
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (101, 1, 'Left Engine CFM56', 'Engine', 'Good', 2015);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (101, 2, 'Right Engine CFM56', 'Engine', 'Needs Inspection', 2015);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (101, 3, 'Main Landing Gear', 'Landing Gear', 'Good', 2015);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (102, 1, 'Left Engine CFM56', 'Engine', 'Excellent', 2016);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (102, 2, 'Right Engine CFM56', 'Engine', 'Excellent', 2016);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (103, 1, 'Weather Radar System', 'Avionics', 'Under Maintenance', 2012);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (103, 2, 'Flight Management Computer', 'Avionics', 'Good', 2012);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (104, 1, 'APU Auxiliary Power Unit', 'Power Unit', 'Good', 2018);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (104, 2, 'Nose Landing Gear', 'Landing Gear', 'Excellent', 2018);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (105, 1, 'Elevator Actuator', 'Flight Control', 'Needs Inspection', 2020);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (105, 2, 'Rudder Control Unit', 'Flight Control', 'Good', 2020);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (106, 1, 'Cabin Air Compressor', 'Environmental Control', 'Good', 2019);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (107, 1, 'Left Winglet', 'Structure', 'Under Maintenance', 2014);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (107, 2, 'Right Winglet', 'Structure', 'Under Maintenance', 2014);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (108, 1, 'Engine Fuel Pump', 'Fuel System', 'Excellent', 2022);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (109, 1, 'Hydraulic Pump A', 'Hydraulic System', 'Needs Inspection', 2011);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (109, 2, 'Hydraulic Pump B', 'Hydraulic System', 'Good', 2011);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (110, 1, 'VHF Communication Radio', 'Avionics', 'Excellent', 2021);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (111, 1, 'Passenger Oxygen System', 'Safety System', 'Good', 2017);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (112, 1, 'Brake Assembly Left', 'Landing Gear', 'Needs Inspection', 2013);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (112, 2, 'Brake Assembly Right', 'Landing Gear', 'Good', 2013);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (113, 1, 'Cargo Door Actuator', 'Hydraulic System', 'Excellent', 2019);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (114, 1, 'Anti-Ice System Valve', 'Environmental Control', 'Under Maintenance', 2015);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (115, 1, 'Left Engine LEAP-1A', 'Engine', 'Excellent', 2023);
INSERT INTO Aircraft_Component (Aircraft_ID, Component_No, Component_Name, Component_Type, Condition_Status, Production_Year) VALUES (115, 2, 'Right Engine LEAP-1A', 'Engine', 'Excellent', 2023);

-- Module 2

-- Department
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (1, 'Avionics', '+905551234501');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (2, 'Engine', '+905551234502');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (3, 'Airframe', '+905551234503');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (4, 'Hydraulics', '+905551234504');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (5, 'Pneumatics', '+905551234505');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (6, 'Landing Gear', '+905551234506');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (7, 'Electrical Systems', '+905551234507');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (8, 'Cabin Interiors', '+905551234508');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (9, 'Paint Shop', '+905551234509');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (10, 'Sheet Metal', '+905551234510');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (11, 'Non-Destructive Testing', '+905551234511');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (12, 'Auxiliary Power Unit', '+905551234512');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (13, 'Flight Controls', '+905551234513');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (14, 'Radar and Communications', '+905551234514');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (15, 'Safety and Quality Assurance', '+905551234515');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (16, 'Line Maintenance', '+905551234516');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (17, 'Base Maintenance', '+905551234517');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (18, 'Maintenance Planning', '+905551234518');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (19, 'Reliability Engineering', '+905551234519');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (20, 'Tooling and Calibration', '+905551234520');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (21, 'Composite Repair', '+905551234521');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (22, 'In-Flight Entertainment', '+905551234522');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (23, 'Oxygen Systems', '+905551234523');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (24, 'Fuel Systems', '+905551234524');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (25, 'Windows and Doors', '+905551234525');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (26, 'Environmental Control', '+905551234526');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (27, 'Fleet Management', '+905551234527');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (28, 'Technical Records', '+905551234528');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (29, 'Supply Chain and Logistics', '+905551234529');
INSERT INTO Department (Department_ID, Department_Name, Contact_Number) VALUES (30, 'Training and Certification', '+905551234530');

-- Staff
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (1, 1, 'Aykut', 'Gök', 'Avionics Technician', DATE '2027-05-15', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (2, 2, 'Aslı', 'Okur', 'Engine Specialist', DATE '2026-11-20', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (3, 3, 'İrem Nil', 'Ataç', 'Airframe Inspector', DATE '2028-02-10', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (4, 4, 'Firdevs', 'Yeşilyurt', 'Hydraulics Engineer', DATE '2026-09-05', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (5, 5, 'Ümran', 'Çağ', 'Pneumatics Tech', DATE '2029-01-30', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (6, 6, 'Liam', 'O''Connor', 'Landing Gear Expert', DATE '2027-08-12', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (7, 7, 'Burak', 'Şahin', 'Electrical Engineer', DATE '2026-12-01', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (8, 8, 'Sophia', 'Müller', 'Cabin Interior Tech', DATE '2028-04-22', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (9, 9, 'Can', 'Çelik', 'Paint Specialist', DATE '2027-07-18', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (10, 10, 'Wei', 'Chen', 'Sheet Metal Worker', DATE '2026-10-15', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (11, 11, 'Zeynep', 'Arslan', 'NDT Inspector', DATE '2028-11-30', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (12, 12, 'Oliver', 'Brown', 'APU Technician', DATE '2027-03-05', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (13, 13, 'Mehmet', 'Öztürk', 'Flight Controls Eng', DATE '2029-06-11', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (14, 14, 'Isabella', 'Rossi', 'Radar Systems Tech', DATE '2026-12-25', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (15, 15, 'Fatma', 'Yıldız', 'Quality Assurance Mgr', DATE '2030-01-15', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (16, 16, 'Lucas', 'Silva', 'Line Maintenance Tech', DATE '2027-09-09', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (17, 17, 'Hakan', 'Erdoğan', 'Base Maint Supervisor', DATE '2028-05-14', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (18, 18, 'Mia', 'Jensen', 'Maintenance Planner', DATE '2026-08-20', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (19, 19, 'Kemal', 'Polat', 'Reliability Analyst', DATE '2029-02-28', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (20, 20, 'Yuki', 'Takahashi', 'Calibration Tech', DATE '2027-11-11', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (21, 21, 'Cem', 'Kılıç', 'Composite Tech', DATE '2028-10-05', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (22, 22, 'Amelia', 'Davies', 'IFE Specialist', DATE '2026-12-10', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (23, 23, 'Selin', 'Aydın', 'Oxygen Systems Eng', DATE '2029-07-22', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (24, 24, 'Ethan', 'Wilson', 'Fuel Systems Tech', DATE '2027-04-16', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (25, 25, 'Emre', 'Bulut', 'Doors Specialist', DATE '2028-01-08', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (26, 26, 'Chloe', 'Martin', 'ECS Engineer', DATE '2026-10-31', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (27, 27, 'Deniz', 'Koç', 'Fleet Manager', DATE '2030-03-15', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (28, 28, 'Alexander', 'Ivanov', 'Technical Records Clerk', DATE '2027-06-25', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (29, 29, 'Ozan', 'Turan', 'Logistics Coordinator', DATE '2028-09-12', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (30, 30, 'Harper', 'Lee', 'Training Instructor', DATE '2029-12-05', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (31, 15, 'Mert', 'Yılmaz', 'Safety Inspector', DATE '2028-05-10', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (32, 8, 'Emma', 'Watson', 'Cabin Trim Specialist', DATE '2027-11-22', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (33, 24, 'Kaan', 'Özdemir', 'Fuel Systems Inspector', DATE '2029-01-15', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (34, 2, 'David', 'Miller', 'Engine Mechanic', DATE '2026-08-30', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (35, 12, 'Ayşenur', 'Çetin', 'APU Engineer', DATE '2030-03-12', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (36, 18, 'Hiroshi', 'Sato', 'Maintenance Scheduler', DATE '2027-06-18', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (37, 1, 'Canan', 'Kurt', 'Avionics Diagnostician', DATE '2028-12-05', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (38, 9, 'Pablo', 'Garcia', 'Paint Shop Supervisor', DATE '2029-09-09', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (39, 14, 'Barış', 'Aksoy', 'Comms Technician', DATE '2027-02-28', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (40, 21, 'Sophie', 'Laurent', 'Composite Inspector', DATE '2028-07-14', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (41, 3, 'Gökhan', 'Yavuz', 'Airframe Welder', DATE '2026-10-05', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (42, 29, 'James', 'Anderson', 'Logistics Analyst', DATE '2030-01-20', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (43, 7, 'Zehra', 'Güneş', 'Electrical Tech', DATE '2027-04-16', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (44, 26, 'Lars', 'Nielsen', 'ECS Specialist', DATE '2029-11-30', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (45, 5, 'Onur', 'Taş', 'Pneumatics Engineer', DATE '2028-08-25', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (46, 11, 'Maria', 'Silva', 'NDT Specialist', DATE '2027-05-01', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (47, 16, 'Ece', 'Köse', 'Line Maintenance Mgr', DATE '2030-06-10', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (48, 30, 'William', 'Taylor', 'Training Coordinator', DATE '2028-02-14', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (49, 25, 'Kerem', 'Işık', 'Doors Technician', DATE '2026-12-12', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (50, 19, 'Anna', 'Kowalski', 'Reliability Engineer', DATE '2029-04-08', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (51, 12, 'Barış', 'Aksoy', 'Avionics Technician', DATE '2028-05-10', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (52, 3, 'Barış', 'Yavuz', 'Airframe Welder', DATE '2029-01-15', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (53, 7, 'Zehra', 'Güneş', 'Electrical Tech', DATE '2027-11-20', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (54, 16, 'Zehra', 'Güneş', 'Line Maintenance Tech', DATE '2028-03-22', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (55, 11, 'Maria', 'Silva', 'NDT Inspector', DATE '2026-09-30', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (56, 9, 'Gökhan', 'Yavuz', 'Comms Technician', DATE '2027-12-01', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (57, 21, 'Ece', 'Aksoy', 'Composite Inspector', DATE '2030-02-18', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (58, 30, 'William', 'Taylor', 'Training Coordinator', DATE '2029-08-14', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (59, 29, 'William', 'Taylor', 'Logistics Analyst', DATE '2028-10-10', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (60, 5, 'Onur', 'Taş', 'Pneumatics Tech', DATE '2027-06-05', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (61, 25, 'Sophie', 'Laurent', 'Doors Technician', DATE '2028-11-11', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (62, 19, 'Kerem', 'Işık', 'Reliability Engineer', DATE '2031-01-25', 3);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (63, 26, 'Anna', 'Kowalski', 'ECS Specialist', DATE '2029-07-07', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (64, 16, 'Lars', 'Nielsen', 'Line Maintenance Tech', DATE '2028-04-12', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (65, 3, 'Gökhan', 'Köse', 'Airframe Welder', DATE '2027-03-15', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (66, 16, 'Ece', 'Köse', 'Line Maintenance Mgr', DATE '2030-12-01', 5);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (67, 29, 'James', 'Anderson', 'Supply Chain Analyst', DATE '2029-05-20', 4);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (68, 11, 'Maria', 'Silva', 'NDT Specialist', DATE '2028-09-09', 2);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (69, 7, 'Barış', 'Aksoy', 'Electrical Tech', DATE '2026-11-11', 1);
INSERT INTO Staff (Staff_ID, Department_ID, First_Name, Last_Name, Role, Cert_Expiry_Date, Seniority_Level) VALUES (70, 5, 'Zehra', 'Taş', 'Pneumatics Engineer', DATE '2030-10-30', 3);

-- Module 3

-- Supplier  (25 rows)
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (1, 'AeroParts Global', 'sales1@aeroparts.com', 'QC-10000');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (2, 'SkyTech Components', 'sales2@skytech.com', 'QC-10007');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (3, 'TurkAvia Supply', 'sales3@turkavia.com', 'QC-10014');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (4, 'Pratt Spares Ltd', 'sales4@pratt.com', 'QC-10021');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (5, 'Boeing Approved Parts', 'sales5@boeing.com', 'QC-10028');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (6, 'Airbus Components Co', 'sales6@airbus.com', 'QC-10035');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (7, 'SafranLine Supply', 'sales7@safranline.com', 'QC-10042');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (8, 'Honeywell Aero', 'sales8@honeywell.com', 'QC-10049');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (9, 'Collins Spares', 'sales9@collins.com', 'QC-10056');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (10, 'GE Aviation Parts', 'sales10@ge.com', 'QC-10063');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (11, 'Anatolia Aero', 'sales11@anatolia.com', 'QC-10070');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (12, 'Bosphorus Aviation', 'sales12@bosphorus.com', 'QC-10077');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (13, 'MRO Solutions', 'sales13@mro.com', 'QC-10084');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (14, 'JetStream Parts', 'sales14@jetstream.com', 'QC-10091');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (15, 'Falcon Components', 'sales15@falcon.com', 'QC-10098');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (16, 'Marmara Aerospace', 'sales16@marmara.com', 'QC-10105');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (17, 'Aegean Aero Supply', 'sales17@aegean.com', 'QC-10112');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (18, 'Continental Spares', 'sales18@continental.com', 'QC-10119');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (19, 'Aviation Depot TR', 'sales19@aviation.com', 'QC-10126');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (20, 'Eurojet Parts', 'sales20@eurojet.com', 'QC-10133');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (21, 'NorthWing Supply', 'sales21@northwing.com', 'QC-10140');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (22, 'Delta Aero Components', 'sales22@delta.com', 'QC-10147');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (23, 'Pinnacle Aviation', 'sales23@pinnacle.com', 'QC-10154');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (24, 'TurboFix Parts', 'sales24@turbofix.com', 'QC-10161');
INSERT INTO Supplier (Supplier_ID, Company_Name, Contact_Email, Quality_Cert_No) VALUES (25, 'Zenith Aerospace', 'sales25@zenith.com', 'QC-10168');

-- Spare_Part  (25 rows)
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (1, 'CFM56 Fan Blade', 57, 20);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (2, 'LEAP-1A Turbine Disk', 5, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (3, 'Brake Pad Set', 21, 5);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (4, 'Main Wheel Tire', 58, 5);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (5, 'Hydraulic Pump Seal', 6, 10);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (6, 'Oxygen Mask Unit', 16, 10);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (7, 'Cockpit Display Unit', 68, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (8, 'Landing Gear Strut', 73, 15);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (9, 'Fuel Filter Element', 10, 20);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (10, 'Air Cycle Machine', 51, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (11, 'Pitot Tube', 39, 12);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (12, 'Cabin Pressure Valve', 14, 20);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (13, 'APU Igniter Plug', 26, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (14, 'Windshield Heater', 25, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (15, 'Elevator Actuator Kit', 57, 20);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (16, 'Rudder Bearing', 4, 15);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (17, 'Engine Oil Filter', 59, 20);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (18, 'VHF Antenna', 71, 12);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (19, 'Battery Pack 24V', 6, 15);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (20, 'Fire Extinguisher Bottle', 26, 10);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (21, 'Cargo Door Seal', 42, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (22, 'Anti-Ice Valve', 19, 12);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (23, 'Navigation Light', 0, 5);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (24, 'Flap Track Roller', 50, 8);
INSERT INTO Spare_Part (Part_ID, Part_Description, Current_Stock, Critical_Threshold) VALUES (25, 'Thrust Reverser Cable', 6, 8);

-- Part_Supplier_Catalog  (30 rows)
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (1, 1, 1);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (2, 1, 5);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (3, 1, 10);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (4, 2, 2);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (5, 2, 4);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (6, 3, 3);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (7, 3, 11);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (8, 3, 17);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (9, 5, 5);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (10, 5, 9);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (11, 8, 8);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (12, 8, 12);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (13, 8, 20);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (14, 3, 7);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (15, 4, 10);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (16, 5, 13);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (17, 6, 16);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (18, 7, 19);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (19, 8, 22);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (20, 9, 25);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (21, 10, 3);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (22, 11, 6);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (23, 12, 9);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (24, 13, 12);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (25, 14, 15);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (26, 15, 18);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (27, 16, 21);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (28, 17, 24);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (29, 18, 2);
INSERT INTO Part_Supplier_Catalog (Catalog_ID, Part_ID, Supplier_ID) VALUES (30, 19, 5);

-- Module 4

INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (1, 'A-Check', 3500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (2, 'B-Check', 15000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (3, 'C-Check', 125000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (4, 'D-Check', 500000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (5, 'Line Maintenance', 800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (6, 'Transit Check', 300.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (7, 'Daily Inspection', 500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (8, 'Weekly Inspection', 1200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (9, 'Engine Wash', 2500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (10, 'Landing Gear Lubrication', 900.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (11, 'Avionics Calibration', 4200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (12, 'Cabin Deep Cleaning', 1100.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (13, 'APU Servicing', 3800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (14, 'Radar Radome Inspection', 1600.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (15, 'Battery Replacement', 750.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (16, 'Oxygen System Pressure Check', 600.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (17, 'Main Landing Gear Tire Replacement', 1800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (18, 'Brake Assembly Overhaul', 5400.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (19, 'Cockpit Windshield Replacement', 12500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (20, 'Pitot Tube Cleaning', 450.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (21, 'Fuel Tank Contamination Check', 2200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (22, 'Emergency Equipment Verification', 650.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (23, 'Cargo Door Seal Lubrication', 350.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (24, 'Engine Oil Filter Change', 850.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (25, 'Hydraulic Fluid Top-up', 400.00);
COMMIT;

INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1001, TO_DATE('2025-11-10', 'YYYY-MM-DD'), 4.5, 101, 6);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1002, TO_DATE('2025-11-15', 'YYYY-MM-DD'), 12.0, 102, 8);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1003, TO_DATE('2025-12-01', 'YYYY-MM-DD'), 45.5, 103, 1);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1004, TO_DATE('2025-12-10', 'YYYY-MM-DD'), 2.0, 104, 7);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1005, TO_DATE('2025-12-22', 'YYYY-MM-DD'), 180.0, 105, 2);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1006, TO_DATE('2026-01-05', 'YYYY-MM-DD'), 8.5, 106, 9);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1007, TO_DATE('2026-01-12', 'YYYY-MM-DD'), 3.0, 107, 25);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1008, TO_DATE('2026-01-20', 'YYYY-MM-DD'), 6.5, 108, 12);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1009, TO_DATE('2026-02-02', 'YYYY-MM-DD'), 24.0, 109, 18);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1010, TO_DATE('2026-02-14', 'YYYY-MM-DD'), 1.5, 110, 20);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1011, TO_DATE('2026-02-28', 'YYYY-MM-DD'), 450.0, 101, 3);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1012, TO_DATE('2026-03-05', 'YYYY-MM-DD'), 5.0, 102, 10);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1013, TO_DATE('2026-03-15', 'YYYY-MM-DD'), 14.5, 103, 11);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1014, TO_DATE('2026-03-22', 'YYYY-MM-DD'), 2.5, 104, 15);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1015, TO_DATE('2026-04-01', 'YYYY-MM-DD'), 35.0, 105, 19);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1016, TO_DATE('2026-04-10', 'YYYY-MM-DD'), 4.0, 106, 22);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1017, TO_DATE('2026-04-18', 'YYYY-MM-DD'), 8.0, 107, 21);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1018, TO_DATE('2026-04-25', 'YYYY-MM-DD'), 3.5, 108, 24);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1019, TO_DATE('2026-05-02', 'YYYY-MM-DD'), 120.0, 109, 4);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1020, TO_DATE('2026-05-08', 'YYYY-MM-DD'), 2.0, 110, 23);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1021, TO_DATE('2026-05-15', 'YYYY-MM-DD'), 48.0, 101, 1);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1022, TO_DATE('2026-05-20', 'YYYY-MM-DD'), 6.0, 102, 17);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1023, TO_DATE('2026-05-25', 'YYYY-MM-DD'), 9.5, 103, 13);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1024, TO_DATE('2026-05-28', 'YYYY-MM-DD'), 3.0, 104, 16);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1025, TO_DATE('2026-05-30', 'YYYY-MM-DD'), 18.0, 105, 14);

-- Module 5
-- System_User  (25 rows)
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (1, 1, 'aykut.gok', 'HASH_1013x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (2, 2, 'asli.okur', 'HASH_1026x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (3, 3, 'irem.atac', 'HASH_1039x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (4, 4, 'firdevs.yesilyurt', 'HASH_1052x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (5, 5, 'umran.cag', 'HASH_1065x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (6, 6, 'liam.oconnor', 'HASH_1078x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (7, 7, 'burak.sahin', 'HASH_1091x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (8, 8, 'sophia.muller', 'HASH_1104x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (9, 9, 'can.celik', 'HASH_1117x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (10, 10, 'wei.chen', 'HASH_1130x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (11, 11, 'zeynep.arslan', 'HASH_1143x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (12, 12, 'oliver.brown', 'HASH_1156x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (13, 13, 'mehmet.ozturk', 'HASH_1169x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (14, 14, 'isabella.rossi', 'HASH_1182x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (15, 15, 'fatma.yildiz', 'HASH_1195x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (16, 16, 'lucas.silva', 'HASH_1208x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (17, 17, 'hakan.erdogan', 'HASH_1221x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (18, 18, 'mia.jensen', 'HASH_1234x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (19, 19, 'kemal.polat', 'HASH_1247x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (20, 20, 'yuki.takahashi', 'HASH_1260x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (21, 21, 'cem.kilic', 'HASH_1273x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (22, 22, 'amelia.davies', 'HASH_1286x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (23, 23, 'selin.aydin', 'HASH_1299x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (24, 24, 'ethan.wilson', 'HASH_1312x9f');
INSERT INTO System_User (User_ID, Staff_ID, Username, Password_Hash) VALUES (25, 25, 'emre.bulut', 'HASH_1325x9f');



-- Maintenance_Crew  (62 rows)
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (1, 1001, 1);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (2, 1002, 3);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (3, 1002, 8);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (4, 1002, 13);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (5, 1003, 5);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (6, 1004, 7);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (7, 1004, 12);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (8, 1005, 9);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (9, 1005, 14);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (10, 1005, 19);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (11, 1006, 11);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (12, 1006, 16);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (13, 1007, 13);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (14, 1008, 15);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (15, 1008, 20);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (16, 1008, 25);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (17, 1009, 17);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (18, 1010, 19);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (19, 1010, 24);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (20, 1010, 29);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (21, 1011, 21);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (22, 1011, 26);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (23, 1011, 1);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (24, 1012, 23);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (25, 1012, 28);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (26, 1012, 3);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (27, 1013, 25);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (28, 1013, 30);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (29, 1014, 27);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (30, 1015, 29);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (31, 1015, 4);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (32, 1016, 1);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (33, 1016, 6);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (34, 1017, 3);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (35, 1018, 5);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (36, 1019, 7);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (37, 1020, 9);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (38, 1020, 14);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (39, 1020, 19);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (40, 1021, 11);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (41, 1021, 16);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (42, 1022, 13);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (43, 1022, 18);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (44, 1023, 15);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (45, 1023, 20);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (46, 1024, 17);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (47, 1024, 22);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (48, 1025, 19);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (49, 1025, 24);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (50, 1016, 21);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (51, 1016, 26);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (52, 1016, 10);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (53, 1017, 23);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (54, 1018, 25);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (55, 1018, 30);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (56, 1018, 15);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (57, 1019, 27);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (58, 1019, 2);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (59, 1019, 17);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (60, 1010, 30);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (61, 1010, 4);
INSERT INTO Maintenance_Crew (Crew_ID, Maintenance_ID, Staff_ID) VALUES (62, 1010, 9);

-- Maintenance_Parts_Used  (61 rows)
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (1, 1001, 1, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (2, 1002, 2, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (3, 1002, 9, 3);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (4, 1003, 3, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (5, 1004, 4, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (6, 1005, 5, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (7, 1005, 12, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (8, 1005, 19, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (9, 1006, 6, 3);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (10, 1007, 7, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (11, 1007, 14, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (12, 1008, 8, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (13, 1008, 15, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (14, 1009, 9, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (15, 1010, 10, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (16, 1010, 17, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (17, 1010, 24, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (18, 1011, 11, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (19, 1012, 12, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (20, 1012, 19, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (21, 1013, 13, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (22, 1013, 20, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (23, 1014, 14, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (24, 1014, 21, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (25, 1015, 15, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (26, 1015, 22, 3);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (27, 1016, 16, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (28, 1016, 23, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (29, 1017, 17, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (30, 1017, 24, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (31, 1017, 6, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (32, 1018, 18, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (33, 1019, 19, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (34, 1019, 1, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (35, 1020, 20, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (36, 1020, 2, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (37, 1020, 9, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (38, 1021, 21, 3);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (39, 1021, 3, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (40, 1021, 10, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (41, 1022, 22, 4);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (42, 1022, 4, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (43, 1022, 11, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (44, 1023, 23, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (45, 1024, 24, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (46, 1024, 6, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (47, 1024, 13, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (48, 1025, 25, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (49, 1025, 7, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (50, 1025, 14, 2);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (51, 1016, 1, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (52, 1016, 8, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (53, 1017, 2, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (54, 1018, 3, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (55, 1018, 10, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (56, 1018, 17, 1);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (57, 1019, 4, 6);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (58, 1019, 11, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (59, 1010, 5, 5);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (60, 1010, 12, 3);
INSERT INTO Maintenance_Parts_Used (Detail_ID, Maintenance_ID, Part_ID, Quantity_Used) VALUES (61, 1010, 19, 3);

COMMIT;
