
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (1, 'A-Check', 3500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (2, 'B-Check', 15000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (3, 'C-Check', 125000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (4, 'D-Check', 500000.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (5, 'Line Maintenance', 800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (6, 'Transit Check', 300.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (7, 'Daily Inspection', 500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (8, 'Weekly Inspection', 1200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (9, 'Engine Wash', 2500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (10, 'Landing Gear Lubrication', 900.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (11, 'Avionics Calibration', 4200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (12, 'Cabin Deep Cleaning', 1100.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (13, 'APU Servicing', 3800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (14, 'Radar Radome Inspection', 1600.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (15, 'Battery Replacement', 750.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (16, 'Oxygen System Pressure Check', 600.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (17, 'Main Landing Gear Tire Replacement', 1800.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (18, 'Brake Assembly Overhaul', 5400.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (19, 'Cockpit Windshield Replacement', 12500.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (20, 'Pitot Tube Cleaning', 450.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (21, 'Fuel Tank Contamination Check', 2200.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (22, 'Emergency Equipment Verification', 650.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (23, 'Cargo Door Seal Lubrication', 350.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (24, 'Engine Oil Filter Change', 850.00);
INSERT INTO MAINTENANCE_TYPE (Type_ID, Type_Description, Standard_Cost) VALUES (25, 'Hydraulic Fluid Top-up', 400.00);
COMMIT;

INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1001, TO_DATE('2025-11-10', 'YYYY-MM-DD'), 4.5, 101, 6);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1002, TO_DATE('2025-11-15', 'YYYY-MM-DD'), 12.0, 102, 8);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1003, TO_DATE('2025-12-01', 'YYYY-MM-DD'), 45.5, 103, 1);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1004, TO_DATE('2025-12-10', 'YYYY-MM-DD'), 2.0, 104, 7);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1005, TO_DATE('2025-12-22', 'YYYY-MM-DD'), 180.0, 105, 2);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1006, TO_DATE('2026-01-05', 'YYYY-MM-DD'), 8.5, 106, 9);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1007, TO_DATE('2026-01-12', 'YYYY-MM-DD'), 3.0, 107, 25);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1008, TO_DATE('2026-01-20', 'YYYY-MM-DD'), 6.5, 108, 12);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1009, TO_DATE('2026-02-02', 'YYYY-MM-DD'), 24.0, 109, 18);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1010, TO_DATE('2026-02-14', 'YYYY-MM-DD'), 1.5, 110, 20);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1011, TO_DATE('2026-02-28', 'YYYY-MM-DD'), 450.0, 101, 3);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1012, TO_DATE('2026-03-05', 'YYYY-MM-DD'), 5.0, 102, 10);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1013, TO_DATE('2026-03-15', 'YYYY-MM-DD'), 14.5, 103, 11);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1014, TO_DATE('2026-03-22', 'YYYY-MM-DD'), 2.5, 104, 15);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1015, TO_DATE('2026-04-01', 'YYYY-MM-DD'), 35.0, 105, 19);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1016, TO_DATE('2026-04-10', 'YYYY-MM-DD'), 4.0, 106, 22);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1017, TO_DATE('2026-04-18', 'YYYY-MM-DD'), 8.0, 107, 21);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1018, TO_DATE('2026-04-25', 'YYYY-MM-DD'), 3.5, 108, 24);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1019, TO_DATE('2026-05-02', 'YYYY-MM-DD'), 120.0, 109, 4);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1020, TO_DATE('2026-05-08', 'YYYY-MM-DD'), 2.0, 110, 23);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1021, TO_DATE('2026-05-15', 'YYYY-MM-DD'), 48.0, 101, 1);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1022, TO_DATE('2026-05-20', 'YYYY-MM-DD'), 6.0, 102, 17);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1023, TO_DATE('2026-05-25', 'YYYY-MM-DD'), 9.5, 103, 13);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1024, TO_DATE('2026-05-28', 'YYYY-MM-DD'), 3.0, 104, 16);
INSERT INTO MAINTENANCE_LOG (Maintenance_ID, Operation_Date, Total_Man_Hours, Aircraft_ID, Type_ID) VALUES (1025, TO_DATE('2026-05-30', 'YYYY-MM-DD'), 18.0, 105, 14);

COMMIT;